spring:
  application:
    name: gestion-formation

  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_formation
    username: postgres
    password: system
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:rezguihoussem67@gmail.com}
    password: ${MAIL_PASSWORD:zxtl lprq wsdw awov} # ⚠️ met le vrai en variable env
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  mail:
    from: ${MAIL_FROM:Excellent Training <rezguihoussem67@gmail.com>}

server:
  port: 8080